<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Route;

class RouteSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $routes = [
            [
                "title" => "Dashboard",
                "icon" => "heroicon-s-squares-2x2",
                "route" => "master.dashboard",
                "parent_id" => null,
                "menu_id" => 1,
            ],
            // [
            //     "title" => "User",
            //     "icon" => "heroicon-s-user",
            //     "route" => "master.user",
            //     "parent_id" => null,
            //     "menu_id" => 1,
            // ],
            // [
            //     "title" => "Level",
            //     "icon" => "heroicon-s-queue-list",
            //     "route" => "master.user.level",
            //     "parent_id" => "2",
            //     "menu_id" => 1,
            // ],
            // [
            //     "title" => "Users",
            //     "icon" => "heroicon-s-queue-list",
            //     "route" => "master.user.users",
            //     "parent_id" => "2",
            //     "menu_id" => 1,
            // ],
            // [
            //     "title" => "Reference",
            //     "icon" => "heroicon-s-adjustments-horizontal",
            //     "route" => "master.reference",
            //     "parent_id" => null,
            //     "menu_id" => 1,
            // ],
            // [
            //     "title" => "Classroom",
            //     "icon" => "heroicon-s-queue-list",
            //     "route" => "master.reference.classroom",
            //     "parent_id" => 5,
            //     "menu_id" => 1,
            // ],
            // [
            //     "title" => "Class",
            //     "icon" => "heroicon-s-queue-list",
            //     "route" => "master.reference.clas",
            //     "parent_id" => 5,
            //     "menu_id" => 1,
            // ],
            // [
            //     "title" => "Group",
            //     "icon" => "heroicon-s-queue-list",
            //     "route" => "master.reference.group",
            //     "parent_id" => 5,
            //     "menu_id" => 1,
            // ],
            // [
            //     "title" => "Collager Status",
            //     "icon" => "heroicon-s-queue-list",
            //     "route" => "master.reference.collager-status",
            //     "parent_id" => 5,
            //     "menu_id" => 1,
            // ],
            // [
            //     "title" => "Lecturer Status",
            //     "icon" => "heroicon-s-queue-list",
            //     "route" => "master.reference.lecturer-status",
            //     "parent_id" => 5,
            //     "menu_id" => 1,
            // ],
            // [
            //     "title" => "Entrance",
            //     "icon" => "heroicon-s-queue-list",
            //     "route" => "master.reference.entrance",
            //     "parent_id" => 5,
            //     "menu_id" => 1,
            // ],
            // [
            //     "title" => "Setting",
            //     "icon" => "heroicon-s-cog-6-tooth",
            //     "route" => "master.setting",
            //     "parent_id" => null,
            //     "menu_id" => 1,
            // ],
            // [
            //     "title" => "Campus Profile",
            //     "icon" => "heroicon-s-queue-list",
            //     "route" => "master.setting.campus-profile",
            //     "parent_id" => 12,
            //     "menu_id" => 1,
            // ],
            // [
            //     "title" => "Academic Year",
            //     "icon" => "heroicon-s-queue-list",
            //     "route" => "master.setting.academic-year",
            //     "parent_id" => 12,
            //     "menu_id" => 1,
            // ],
            // [
            //     "title" => "Menu",
            //     "icon" => "heroicon-s-queue-list",
            //     "route" => "master.setting.menu",
            //     "parent_id" => 12,
            //     "menu_id" => 1,
            // ],
            // [
            //     "title" => "Schedule Form",
            //     "icon" => "heroicon-s-queue-list",
            //     "route" => "master.setting.schedule-form",
            //     "parent_id" => 12,
            //     "menu_id" => 1,
            // ],
            // [
            //     "title" => "Value Component",
            //     "icon" => "heroicon-s-queue-list",
            //     "route" => "master.setting.value-component",
            //     "parent_id" => 12,
            //     "menu_id" => 1,
            // ],
            // [
            //     "title" => "Value Weight",
            //     "icon" => "heroicon-s-queue-list",
            //     "route" => "master.setting.value-weight",
            //     "parent_id" => 12,
            //     "menu_id" => 1,
            // ],
            // [
            //     "title" => "Official",
            //     "icon" => "heroicon-s-queue-list",
            //     "route" => "master.setting.official",
            //     "parent_id" => 12,
            //     "menu_id" => 1,
            // ],
            // [
            //     "title" => "Study Program",
            //     "icon" => "heroicon-s-queue-list",
            //     "route" => "master.study-program",
            //     "parent_id" => null,
            //     "menu_id" => 1,
            // ],
            // [
            //     "title" => "Course",
            //     "icon" => "heroicon-s-book-open",
            //     "route" => "master.course",
            //     "parent_id" => null,
            //     "menu_id" => 1,
            // ],
            // [
            //     "title" => "Collager",
            //     "icon" => "heroicon-s-academic-cap",
            //     "route" => "master.collager",
            //     "parent_id" => null,
            //     "menu_id" => 1,
            // ],
            // [
            //     "title" => "Lecturer",
            //     "icon" => "heroicon-s-users",
            //     "route" => "master.lecturer",
            //     "parent_id" => null,
            //     "menu_id" => 1,
            // ],
            // [
            //     "title" => "All",
            //     "icon" => "heroicon-s-users",
            //     "route" => "registrant.all",
            //     "parent_id" => null,
            //     "menu_id" => 2,
            // ],
            // [
            //     "title" => "Passed",
            //     "icon" => "heroicon-s-users",
            //     "route" => "registrant.passed",
            //     "parent_id" => null,
            //     "menu_id" => 2,
            // ],
            // [
            //     "title" => "Generate NIM",
            //     "icon" => "heroicon-s-users",
            //     "route" => "registrant.generate_nim",
            //     "parent_id" => null,
            //     "menu_id" => 2,
            // ],
            // [
            //     "title" => "Invoice",
            //     "icon" => "heroicon-s-banknotes",
            //     "route" => "finance.invoice",
            //     "parent_id" => null,
            //     "menu_id" => 3,
            // ],
            // [
            //     "title" => "Payment",
            //     "icon" => "heroicon-s-currency-dollar",
            //     "route" => "finance.payment",
            //     "parent_id" => null,
            //     "menu_id" => 3,
            // ],
            // [
            //     "title" => "Dispensation",
            //     "icon" => "heroicon-s-exclamation-circle",
            //     "route" => "finance.dispensation",
            //     "parent_id" => null,
            //     "menu_id" => 3,
            // ],
            // [
            //     "title" => "Credit",
            //     "icon" => "heroicon-s-credit-card",
            //     "route" => "finance.credit",
            //     "parent_id" => null,
            //     "menu_id" => 3,
            // ],
            // [
            //     "title" => "Information",
            //     "icon" => "heroicon-s-computer-desktop",
            //     "route" => "transaction.information",
            //     "parent_id" => null,
            //     "menu_id" => 4,
            // ],
            // [
            //     "title" => "Guardianship",
            //     "icon" => "heroicon-s-computer-desktop",
            //     "route" => "transaction.guardianship",
            //     "parent_id" => null,
            //     "menu_id" => 4,
            // ],
            // [
            //     "title" => "Curriculum",
            //     "icon" => "heroicon-s-computer-desktop",
            //     "route" => "transaction.curriculum",
            //     "parent_id" => null,
            //     "menu_id" => 4,
            // ],
            // [
            //     "title" => "Course Schedule",
            //     "icon" => "heroicon-s-computer-desktop",
            //     "route" => "transaction.course_schedule",
            //     "parent_id" => null,
            //     "menu_id" => 4,
            // ],
            // [
            //     "title" => "RPS",
            //     "icon" => "heroicon-s-computer-desktop",
            //     "route" => "transaction.rps",
            //     "parent_id" => null,
            //     "menu_id" => 4,
            // ],
            // [
            //     "title" => "BRP",
            //     "icon" => "heroicon-s-computer-desktop",
            //     "route" => "transaction.brp",
            //     "parent_id" => null,
            //     "menu_id" => 4,
            // ],
            // [
            //     "title" => "KRS",
            //     "icon" => "heroicon-s-computer-desktop",
            //     "route" => "transaction.krs",
            //     "parent_id" => null,
            //     "menu_id" => 4,
            // ],
            // [
            //     "title" => "Value",
            //     "icon" => "heroicon-s-computer-desktop",
            //     "route" => "transaction.value",
            //     "parent_id" => null,
            //     "menu_id" => 4,
            // ],
            // [
            //     "title" => "Thesis",
            //     "icon" => "heroicon-s-computer-desktop",
            //     "route" => "transaction.thesis",
            //     "parent_id" => null,
            //     "menu_id" => 4,
            // ],
            // [
            //     "title" => "Proposal",
            //     "icon" => "heroicon-s-document-duplicate",
            //     "route" => "transaction.thesis.proposal",
            //     "parent_id" => 39,
            //     "menu_id" => 4,
            // ],            [
            //     "title" => "ACC Bim",
            //     "icon" => "heroicon-s-document-duplicate",
            //     "route" => "transaction.thesis.proposal.acc",
            //     "parent_id" => 40,
            //     "menu_id" => 4,
            // ],
            // [
            //     "title" => "List",
            //     "icon" => "heroicon-s-document-duplicate",
            //     "route" => "transaction.thesis.proposal.list",
            //     "parent_id" => 40,
            //     "menu_id" => 4,
            // ],
            // [
            //     "title" => "Schedule",
            //     "icon" => "heroicon-s-document-duplicate",
            //     "route" => "transaction.thesis.proposal.schedule",
            //     "parent_id" => 40,
            //     "menu_id" => 4,
            // ],
            // [
            //     "title" => "Examiner",
            //     "icon" => "heroicon-s-document-duplicate",
            //     "route" => "transaction.thesis.proposal.examiner",
            //     "parent_id" => 40,
            //     "menu_id" => 4,
            // ],
            // [
            //     "title" => "Result",
            //     "icon" => "heroicon-s-document-duplicate",
            //     "route" => "transaction.thesis.proposal.result",
            //     "parent_id" => 40,
            //     "menu_id" => 4,
            // ],
            // [
            //     "title" => "ACC Bim",
            //     "icon" => "heroicon-s-document-duplicate",
            //     "route" => "transaction.thesis.acc",
            //     "parent_id" => 39,
            //     "menu_id" => 4,
            // ],
            // [
            //     "title" => "Library Free",
            //     "icon" => "heroicon-s-document-duplicate",
            //     "route" => "transaction.thesis.library_free",
            //     "parent_id" => 39,
            //     "menu_id" => 4,
            // ],
            // [
            //     "title" => "List",
            //     "icon" => "heroicon-s-document-duplicate",
            //     "route" => "transaction.thesis.list",
            //     "parent_id" => 39,
            //     "menu_id" => 4,
            // ],
            // [
            //     "title" => "Schedule",
            //     "icon" => "heroicon-s-document-duplicate",
            //     "route" => "transaction.thesis.schedule",
            //     "parent_id" => 39,
            //     "menu_id" => 4,
            // ],
            // [
            //     "title" => "Examiner",
            //     "icon" => "heroicon-s-document-duplicate",
            //     "route" => "transaction.thesis.examiner",
            //     "parent_id" => 39,
            //     "menu_id" => 4,
            // ],
            // [
            //     "title" => "Result",
            //     "icon" => "heroicon-s-document-duplicate",
            //     "route" => "transaction.thesis.result",
            //     "parent_id" => 39,
            //     "menu_id" => 4,
            // ],
            // [
            //     "title" => "Recap",
            //     "icon" => "heroicon-s-document-duplicate",
            //     "route" => "transaction.thesis.recap",
            //     "parent_id" => 39,
            //     "menu_id" => 4,
            // ],
            // [
            //     "title" => "Collager Transfer",
            //     "icon" => "heroicon-s-computer-desktop",
            //     "route" => "transaction.collager_transfer",
            //     "parent_id" => null,
            //     "menu_id" => 4,
            // ],
            // [
            //     "title" => "Transcript",
            //     "icon" => "heroicon-s-computer-desktop",
            //     "route" => "transaction.transcript",
            //     "parent_id" => null,
            //     "menu_id" => 4,
            // ],
            // [
            //     "title" => "Yudisium",
            //     "icon" => "heroicon-s-computer-desktop",
            //     "route" => "transaction.yudisium",
            //     "parent_id" => null,
            //     "menu_id" => 4,
            // ],
        ];
        foreach ($routes as $route) {
            Route::create($route);
        }
    }
}
